// students/k3339/laboratory_works/Tsyrulnikov_Artem/Lab4/src/views/Login.vue
<template>
  <v-card max-width="400" class="mx-auto mt-10">
    <v-card-title>Вход</v-card-title>
    <v-card-text>
      <v-form @submit.prevent="submit">
        <v-text-field v-model="form.username" label="Логин" required />
        <v-text-field v-model="form.password" label="Пароль" type="password" required />
        <v-alert v-if="error" type="error" class="mb-3">{{ error }}</v-alert>
        <v-btn type="submit" color="primary" block :loading="loading">Войти</v-btn>
      </v-form>
      <v-btn to="/register" variant="text" block class="mt-2">Регистрация</v-btn>
    </v-card-text>
  </v-card>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'

const auth = useAuthStore()
const router = useRouter()
const form = reactive({ username: '', password: '' })
const loading = ref(false)
const error = ref('')

const submit = async () => {
  loading.value = true
  error.value = ''
  try {
    await auth.login(form.username, form.password)
    router.push('/')
  } catch (e) {
    error.value = 'Неверный логин или пароль'
  }
  loading.value = false
}
</script>

// students/k3339/Miliutin_Nikita/lab4/lab/chicken-frontend/src/pages/Login.jsx
import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { login } from "../api/auth";
import { setToken } from "../utils/token";

export default function Login() {
  const navigate = useNavigate();

  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function onSubmit(e) {
    e.preventDefault();
    setError("");
    setLoading(true);

    try {
      const data = await login(username, password);
      setToken(data.access_token);
      navigate("/");
    } catch (err) {
      const msg =
        err?.response?.data?.detail ||
        err?.message ||
        "Не удалось войти. Проверь логин/пароль.";
      setError(typeof msg === "string" ? msg : "Ошибка входа");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="auth-wrap">
      <div className="card pad auth-card">
        <div className="stack" style={{ gap: 14 }}>
          <div className="stack" style={{ gap: 6 }}>
            <h2 className="auth-title">Вход</h2>
            <div className="auth-sub">Войди в систему</div>
          </div>

          <form className="form" onSubmit={onSubmit}>
            <label>
              Логин
              <input
                className="input"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                autoComplete="username"
                required
              />
            </label>

            <label>
              Пароль
              <input
                className="input"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                autoComplete="current-password"
                type="password"
                required
              />
            </label>

            {error ? <div className="alert error">{error}</div> : null}

            <div className="actions between">
              <button className="btn primary" type="submit" disabled={loading}>
                {loading ? "Входим..." : "Войти"}
              </button>

              <Link className="btn ghost" to="/register">
                Регистрация →
              </Link>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
