// students/K3341/laboratory_works/Marakulin_Andrey/laboratory_work_4/bank_frontend/src/views/Register.vue
<template>
  <v-container>
    <v-card class="mx-auto" max-width="450">
      <v-card-title class="text-h5 success white--text pa-4">
        Регистрация нового пользователя
      </v-card-title>
      <v-card-text>
        <v-form @submit.prevent="register">

          <v-text-field
            v-model="username"
            label="Имя пользователя"
            prepend-icon="mdi-account-plus"
            required
          ></v-text-field>

          <v-text-field
            v-model="email"
            label="Email"
            prepend-icon="mdi-email"
            type="email"
            required
          ></v-text-field>

          <v-text-field
            v-model="password"
            label="Пароль"
            prepend-icon="mdi-lock"
            type="password"
            required
          ></v-text-field>

          <v-alert
            v-if="error"
            type="error"
            dense
            text
            class="mb-3"
          >
            {{ error }}
          </v-alert>

          <v-btn
            color="success"
            class="mr-4"
            type="submit"
            :loading="loading"
          >
            Зарегистрироваться
          </v-btn>
          <v-btn
            text
            @click="$router.push('/login')"
          >
            Уже есть аккаунт?
          </v-btn>
        </v-form>
      </v-card-text>
    </v-card>
  </v-container>
</template>

<script setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import api from '../authApi';

const router = useRouter();
const username = ref('');
const email = ref('');
const password = ref('');
const error = ref(null);
const loading = ref(false);

const register = async () => {
  error.value = null;
  loading.value = true;

  try {
    await api.post('/auth/users/', {
      username: username.value,
      email: email.value,
      password: password.value,
    });

    // Регистрация успешна, перенаправляем на страницу входа
    alert('Регистрация прошла успешно! Теперь войдите в систему.');
    router.push('/login');

  } catch (err) {
    if (err.response && err.response.data) {
        // DRF часто возвращает ошибки валидации в объекте
        const errors = err.response.data;
        if (errors.username) error.value = `Имя пользователя: ${errors.username.join(', ')}`;
        else if (errors.email) error.value = `Email: ${errors.email.join(', ')}`;
        else if (errors.password) error.value = `Пароль: ${errors.password.join(', ')}`;
        else error.value = 'Ошибка при регистрации.';
    } else {
        error.value = 'Произошла ошибка при подключении к серверу.';
    }
    console.error(err);
  } finally {
    loading.value = false;
  }
};
</script>

// students/k3339/Zoteev_Maksim/lab4/teachers_system_react/src/pages/Register.jsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import '../styles/auth.css';

export default function Register() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [rePassword, setRePassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const { register } = useAuth();
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    if (password !== rePassword) {
      setError('Пароли не совпадают');
      return;
    }

    setLoading(true);

    try {
      await register(username, password, rePassword);
      navigate('/');
    } catch (err) {
      const errors = err.response?.data;
      if (errors) {
        const messages = Object.entries(errors)
          .map(([key, value]) => `${value.join(', ')}`)
          .join('\n');
        setError(messages || 'Ошибка регистрации');
      } else {
        setError('Ошибка регистрации. Попробуйте снова.');
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-container">
      <div className="auth-card">
        <div className="auth-header">
          <div className="auth-icon">🏫</div>
          <h1>Регистрация</h1>
          <p>Создайте новый аккаунт</p>
        </div>

        <form onSubmit={handleSubmit} className="auth-form">
          {error && <div className="auth-error">{error}</div>}

          <div className="form-group">
            <label htmlFor="username">Имя пользователя</label>
            <input
              id="username"
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              placeholder="Введите логин"
              required
              autoFocus
            />
          </div>

          <div className="form-group">
            <label htmlFor="password">Пароль</label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Введите пароль"
              required
            />
          </div>

          <div className="form-group">
            <label htmlFor="rePassword">Подтвердите пароль</label>
            <input
              id="rePassword"
              type="password"
              value={rePassword}
              onChange={(e) => setRePassword(e.target.value)}
              placeholder="Повторите пароль"
              required
            />
          </div>

          <button type="submit" className="auth-button" disabled={loading}>
            {loading ? 'Регистрация...' : 'Зарегистрироваться'}
          </button>
        </form>

        <div className="auth-footer">
          <p>
            Уже есть аккаунт? <Link to="/login">Войти</Link>
          </p>
        </div>
      </div>
    </div>
  );
}
