// students/k3339/Zoteev_Maksim/lab4/teachers_system_react/src/pages/Login.jsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import '../styles/auth.css';

export default function Login() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const { login } = useAuth();
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      await login(username, password);
      navigate('/');
    } catch (err) {
      setError(
        err.response?.data?.non_field_errors?.[0] ||
        'Ошибка входа. Проверьте логин и пароль.'
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-container">
      <div className="auth-card">
        <div className="auth-header">
          <div className="auth-icon">🏫</div>
          <h1>Школьная система</h1>
          <p>Вход в панель управления</p>
        </div>

        <form onSubmit={handleSubmit} className="auth-form">
          {error && <div className="auth-error">{error}</div>}

          <div className="form-group">
            <label htmlFor="username">Имя пользователя</label>
            <input
              id="username"
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              placeholder="Введите логин"
              required
              autoFocus
            />
          </div>

          <div className="form-group">
            <label htmlFor="password">Пароль</label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Введите пароль"
              required
            />
          </div>

          <button type="submit" className="auth-button" disabled={loading}>
            {loading ? 'Вход...' : 'Войти'}
          </button>
        </form>

        <div className="auth-footer">
          <p>
            Нет аккаунта? <Link to="/register">Зарегистрироваться</Link>
          </p>
        </div>
      </div>
    </div>
  );
}

// students/K3341/laboratory_works/Ilyas_Javatov/laboratory_work_4/school-management-client/src/components/Auth/Login.vue
<template>
  <v-container class="fill-height" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);">
    <v-row justify="center" align="center">
      <v-col cols="12" sm="8" md="6" lg="4">
        <v-card class="elevation-12" :loading="loading">
          <v-toolbar color="primary" dark flat>
            <v-toolbar-title class="text-h5">
              <v-icon class="mr-2">mdi-school</v-icon>
              Школьная система управления
            </v-toolbar-title>
          </v-toolbar>

          <v-card-text class="pa-6">
            <div class="text-center mb-6">
              <h2 class="text-h4 mb-2">Вход в систему</h2>
              <p class="text-body-1 text-grey">Введите учетные данные</p>
            </div>

            <v-form ref="form" v-model="valid" @submit.prevent="login">
              <v-text-field
                v-model="credentials.username"
                label="Имя пользователя"
                :rules="[rules.required]"
                prepend-icon="mdi-account"
                variant="outlined"
                class="mb-4"
                required
                :disabled="loading"
              />

              <v-text-field
                v-model="credentials.password"
                label="Пароль"
                :type="showPassword ? 'text' : 'password'"
                :rules="[rules.required]"
                prepend-icon="mdi-lock"
                :append-icon="showPassword ? 'mdi-eye' : 'mdi-eye-off'"
                @click:append="showPassword = !showPassword"
                variant="outlined"
                class="mb-2"
                required
                :disabled="loading"
              />

              <v-alert
                v-if="error"
                type="error"
                density="compact"
                class="mb-4"
              >
                {{ error }}
              </v-alert>

              <v-btn
                type="submit"
                color="primary"
                block
                size="large"
                :loading="loading"
                :disabled="!valid || loading"
                class="mt-4"
              >
                <v-icon left>mdi-login</v-icon>
                Войти
              </v-btn>
            </v-form>
          </v-card-text>

          <v-divider />

          <v-card-actions class="pa-4">
            <v-spacer />
            <span class="text-body-2 mr-2">Нет аккаунта?</span>
            <v-btn color="secondary" variant="text" to="/register" :disabled="loading">
              Зарегистрироваться
            </v-btn>
          </v-card-actions>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import { mapActions } from 'vuex'

export default {
  name: 'Login',
  data() {
    return {
      valid: false,
      loading: false,
      showPassword: false,
      error: null,
      credentials: {
        username: '',
        password: ''
      },
      rules: {
        required: value => !!value || 'Обязательное поле'
      }
    }
  },
  methods: {
    ...mapActions('auth', ['login']),

    notify(type, message) {
      if (this.$toast && typeof this.$toast[type] === 'function') {
        this.$toast[type](message)
      }
    },

    async login() {
      if (!this.$refs.form.validate()) return

      this.loading = true
      this.error = null

      try {
        const result = await this.$store.dispatch('auth/login', this.credentials)

        if (result.success) {
          this.notify('success', 'Вход выполнен успешно!')
          this.$router.push('/dashboard')
        } else {
          this.error = result.error?.non_field_errors?.[0] || 'Неверное имя пользователя или пароль'
          this.notify('error', 'Ошибка входа')
        }
      } catch (err) {
        this.error = 'Ошибка подключения к серверу'
        this.notify('error', 'Сервер не отвечает')
      } finally {
        this.loading = false
      }
    }
  }
}
</script>

<style scoped>
.fill-height {
  min-height: 100vh;
}
</style>
