// students/k3339/Miliutin_Nikita/lab4/lab/chicken-frontend/src/pages/Register.jsx
import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { register } from "../api/auth";

export default function Register() {
  const navigate = useNavigate();

  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [password2, setPassword2] = useState("");

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function onSubmit(e) {
    e.preventDefault();
    setError("");

    if (password !== password2) {
      setError("Пароли не совпадают");
      return;
    }

    setLoading(true);
    try {
      await register(username, password);
      navigate("/login");
    } catch (err) {
      const msg =
        err?.response?.data?.detail || err?.message || "Не удалось зарегистрироваться";
      setError(typeof msg === "string" ? msg : "Ошибка регистрации");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="auth-wrap">
      <div className="card pad auth-card">
        <div className="stack" style={{ gap: 14 }}>
          <div className="stack" style={{ gap: 6 }}>
            <h2 className="auth-title">Регистрация</h2>
            <div className="auth-sub">Создай аккаунт сотрудника</div>
          </div>

          <form className="form" onSubmit={onSubmit}>
            <label>
              Логин
              <input
                className="input"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                autoComplete="username"
                required
              />
            </label>

            <label>
              Пароль
              <input
                className="input"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                autoComplete="new-password"
                type="password"
                required
              />
            </label>

            <label>
              Повтори пароль
              <input
                className="input"
                value={password2}
                onChange={(e) => setPassword2(e.target.value)}
                autoComplete="new-password"
                type="password"
                required
              />
            </label>

            {error ? <div className="alert error">{error}</div> : null}

            <div className="actions between">
              <button className="btn primary" type="submit" disabled={loading}>
                {loading ? "Создаём..." : "Зарегистрироваться"}
              </button>

              <Link className="btn ghost" to="/login">
                ← Войти
              </Link>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}

// students/k3339/Mischenko_Maxim/Lr4/airline_client/src/views/Register.vue
<template>
  <v-container class="fill-height justify-center">
    <v-card width="400" class="pa-4">
      <v-card-title>Регистрация</v-card-title>
      <v-card-text>
        <v-form @submit.prevent="register">
          <v-text-field v-model="form.username" label="Логин" required></v-text-field>
          <v-text-field v-model="form.email" label="Email" required></v-text-field>
          <v-text-field v-model="form.password" label="Пароль" type="password" required></v-text-field>
          <v-text-field v-model="form.re_password" label="Повторите пароль" type="password" required></v-text-field>
          <v-btn type="submit" color="primary" block class="mt-4">Создать аккаунт</v-btn>
        </v-form>
      </v-card-text>
      <v-card-actions>
        <v-btn to="/login" variant="text" block>Уже есть аккаунт? Войти</v-btn>
      </v-card-actions>
    </v-card>
  </v-container>
</template>

<script setup>
import { ref } from 'vue';
import api from '../api';
import { useRouter } from 'vue-router';

const router = useRouter();
const form = ref({ username: '', email: '', password: '' });

const register = async () => {
  try {
    await api.post('/auth/users/', form.value);
    alert('Успешно! Теперь войдите.');
    router.push('/login');
  } catch (e) {
    alert('Ошибка: ' + JSON.stringify(e.response.data));
  }
};
</script>
